name: ferro_VAE
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - h5py
  - ipywidgets
  - matplotlib
  - ipympl
  - jupyterlab
  - jupyterlab-myst
  - 'nodejs>=20,<21'
  - mystmd
  - seaborn
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cpu
    - wget
    - gdown
    - torch
    - torchvision
    - torchaudio
    - git+https://github.com/pycroscopy/atomai
    - git+https://github.com/ziatdinovmax/pyroVED@main


