name: ferro_VAE
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - h5py
  - ipywidgets
  - matplotlib
  - ipympl
  - jupyterlab
  - jupyterlab-myst
  - 'nodejs>=20,<21'
  - mystmd
  - torchvision
  - torchaudio
  - seaborn
  - pip
  - gdown
  - pip:
    - wget
    - git+https://github.com/pycroscopy/atomai
    - git+https://github.com/ziatdinovmax/pyroVED@main


